### ISSUE TITLE
Implement Profile Drop Down

### ISSUE THREAD

**Issue by cyrusdiego** [UAlbertaCompEClub/compe-plus#112]
* Logout button
* button to show settings 
![image](https://user-images.githubusercontent.com/32345990/122689205-2c3be600-d1de-11eb-90e2-b8934c1f0637.png)

**Comment by armiantos** [comment]
Reference to similar implementation
* [Component demo](https://material-ui.com/components/app-bar/#app-bar-with-a-primary-search-field)

Component to use
* [React Menu component](https://material-ui.com/components/menus/)

Tips
* Use `useState` for the `open` field in `<Menu open={open} ...>`
* Handlers like `onClick` are usually single argument functions (e.g. `onClick={(event) => console.debug(e)}`

**Comment by armiantos** [comment]
Deliverables
1. `UserProfile` component under `src/components/auth`
2. `UserProfile` should be displayed when the user is logged in
3. Clicking on `UserProfile` should bring up a menu
4. Menu should present a logout entry
5. Clicking on logout should logout the user and redisplay the Login button
