### ISSUE TITLE
UI broken on registration page

### ISSUE THREAD

**Issue by KateVlaar** [UAlbertaCompEClub/compe-plus#245]
Year, specialty and submit button all facing major alignment issues. After year and specialty entered, elements are squished together. Nit: White text on sage is kinda hard to read. 

![image](https://user-images.githubusercontent.com/44733046/133019633-44b8d983-089a-4f83-a474-a22c486d61d3.png)
![image](https://user-images.githubusercontent.com/44733046/133019719-35384f47-628d-4cdd-b5fc-a28ee948c41f.png)

**Comment by armiantos** [comment]
Related to #190

**Comment by armiantos** [comment]
Closed by #248
