### ISSUE TITLE
RFC: Auth and RBAC

### ISSUE THREAD

**Issue by cyrusdiego** [UAlbertaCompEClub/compe-plus#42]
- write a RFC for design

**Comment by armiantos** [comment]
[Setting up Auth0 Express middleware to verify access token](https://auth0.com/docs/quickstart/backend/nodejs/01-authorization)
[How to get access token as a client](https://auth0.com/docs/quickstart/spa/react/02-calling-an-api)

**Comment by armiantos** [comment]
TODO: Read on RBAC using Auth0 [source](https://auth0.com/blog/node-js-and-typescript-tutorial-secure-an-express-api/#Configure-Role-Based-Access-Control--RBAC-)

**Comment by armiantos** [comment]
# Overview

When a user authenticates themselves from our front-end using Auth0, they will pass an `audience` parameter ([Learn more](https://auth0.com/docs/quickstart/spa/react/02-calling-an-api)). This [`audience`](https://auth0.com/docs/glossary#audience) parameter is the API identifier we define when creating a new custom API in Auth0. 

Once the user is authenticated, they can now silently request access tokens from our custom API using the `audience` from before and set of permission claims or `scope`. The token will be attached to an Authorization field in the request header to our back-end. [Learn more about getting an access token for our APIs](https://auth0.com/docs/quickstart/spa/react/02-calling-an-api#get-an-access-token)

On a secure request, the back-end uses jwtChecking to verify the authenticity of the token. It checks if the issuer was our custom API in Auth0 and whether the `audience` field is correct. This is done using the npm package `jwks.expressJwtSecret` recommended by Auth0. Additionally we can ensure scopes on an endpoint basis using `jwtAuthz`. [Learn more about validating access tokens](https://auth0.com/docs/quickstart/backend/nodejs#validate-access-tokens).

# FAQ

> What makes it more secure?

1. The `audience` field to get an API token from Auth0 is only known by us
2. The `scopes` or permissions is only known by us
3. If we perform additional check if we can recognize the user

# Additional resources
* [Protecting an API](https://auth0.com/docs/microsites/protect-api/protect-api)
* [SPA + API integration](https://auth0.com/docs/architecture-scenarios/spa-api)

**Comment by calebschoepp** [comment]
@armiantos Just read over this. At a high level I like the approach. I may come back and drop some questions here and I may also drop them in #55 .
