### ISSUE TITLE
Ramp up 

### ISSUE THREAD

**Issue by cyrusdiego** [UAlbertaCompEClub/compe-plus#48]
- Setup WSL 
- Clone repo 
- Build project 
- Run localhost for front end and back end (individually)
- Run tests 
- Curl (or postman) the sample endpoint 
- Git crash course:
   -  Enter your name in README.md as first PR

**Comment by armiantos** [comment]
- ~~Setup WSL ~~
- ~~Clone repo ~~
- ~~Build project ~~
- ~~Run localhost for front end~~ and back end (individually)
- Run tests 
- Curl (or postman) the sample endpoint 
- ~~Git crash course: ~~
   -  ~~Enter your name in README.md as first PR  ~~
