### ISSUE TITLE
Create registration form

### ISSUE THREAD

**Issue by armiantos** [UAlbertaCompEClub/compe-plus#97]
* Create UI components for the following:
  * First name
  * Last name
  * Current year
  * Specialization program
* Store state using `useState` or uncontrolled until #96 is integrated / developed

**Comment by armiantos** [comment]
![image](https://user-images.githubusercontent.com/43416725/125887041-d2de09b6-87d4-4cf2-bbdb-5e4ca56745af.png)

**Comment by calebschoepp** [comment]
Should not include first name or last name. We can get that from the Id token from Auth0
